### ISSUE TITLE
Criar função para inicializar uma thread com o servidor HTTP

### ISSUE THREAD

**Issue by Bumbleblo** [amenezes/discovery-client#1]
Como toda aplicação consul necessita inicializar um HTTP server para realizar o *health* *checking*, o consul client poderia ter uma função que levantaria esse servidor HTTP. 

Proponho que a função de registro ou uma função periférica inicialize o servidor em uma nova thread. Com essa abordagem, caso a thread main morra as threads filhas também seriam destruídas fazendo com que o *health* *checking* ficasse negativado.

Para o servidor HTTP proponho o SimpleHTTPRequestHandler, essa implementação não tem problema em ser inicializada em outras thread (diferente do [Flask](http://flask.pocoo.org/docs/0.12/design/#thread-locals)).

Segue um exemplo dessa implementação  

```python
class HealthServer(SimpleHTTPRequestHandler):
    def do_GET(self):   
        self.send_response(200)
        self.send_header('Content-type','text/html')
        self.end_headers()
 
        self.wfile.write(bytes(json.dumps({"status":"ok"}), 'utf8'))
        return json.dumps({"status" :"OK"})

def run_server():

    httpd = socketserver.TCPServer(('0.0.0.0', 5000), HealthServer)
    httpd.path = '/manage/health'
    httpd.serve_forever()

```

**Comment by amenezes** [comment]
@Bumbleblo,

O propósito da lib é encapsular funções de alto nível para interações, no momento, com o Consul utilizando a lib [python-consul](https://python-consul.readthedocs.io/).

A biblioteca [base](https://python-consul.readthedocs.io/en/latest/#clients) possui suporte para clientes síncronos (_standard_) e assíncronos (_vanilla_, _gevent_, _tornado_ e _asyncio_).

Infelizmente, a disponibilização de um servidor HTTP em conjunto com a biblioteca está fora de seu escopo.
