### ISSUE TITLE
Melhoria na função consul_is_health no pacote client.py

### ISSUE THREAD

**Issue by Bumbleblo** [amenezes/discovery-client#2]
O pacote client.py não está criando o looping para a conferencia/re-registro do consul, proponho a utilização do pacote [threading](https://docs.python.org/3.5/library/threading.html) para inicializar um looping na linha na linha 69 do pacote em uma nova thread que iria realizar essa tarefa, seguindo o mesmo conceito do discoveryio.py.

**Comment by amenezes** [comment]
@Bumbleblo, 

O loop pode ser criado em algum ponto de sua aplicação, conforme exemplo relacionado no [README](https://github.com/amenezes/discovery-client). Não há restrição neste sentido imposta pela lib.

Contudo, a partir da versão [0.2.1](https://github.com/amenezes/discovery-client/releases/tag/0.2.1) o loop está presente no client padrão, mas observe que o método empregado atualmente, de verificação de status do consul para reconexão, é gerenciado fora da lib. No exemplo citado do cliente que utiliza [asyncio](https://docs.python.org/3/library/asyncio.html), veja que é necessário criar uma tarefa para que o loop de eventos em um dado momento execute o método. 

Acredito que a abordagem utilizando asyncio seja melhor em um cenário de concorrência, mas talvez você possa seguir o mesmo princípio caso queira utilizar threads.

exemplo usando asyncio:

````python
...

async def service_discovery(app):
    app.loop.create_task(dc.register('aio-client', 5000))
    asyncio.sleep(15)
    app.loop.create_task(dc.consul_is_healthy()) # insere a tarefa no loop

...
````

exemplo usando thread com Flask:

````python
...

@app.before_first_request
def enable_service_registry():
    def probe_discovery_connection():
        dc.consul_is_healthy()
    thread = threading.Thread(target=probe_discovery_connection)
    thread.start()

...
````

Veja se os [exemplos](https://github.com/amenezes/discovery-client/tree/master/examples) te auxiliam em algo.

**Comment by Bumbleblo** [comment]
Nós do GPAM necessitamos para a arquitetura de nosso sistema no projeto Victor dessas features no client-discovery de forma **síncrona**:

feature| python-consul | discovery-client | 
-|-|-
encontrar outros serviços| :heavy_check_mark: | :heavy_check_mark: 
registrar um serviço| :heavy_check_mark:  | :heavy_check_mark: 
inspecionar e registrar caso o serviço do consul caia| :x: | :x: 
iniciar o servidor HTTP server para o health cheking | :x: | :x: 

Como essas necessidades não são atendidas pelo client, analisamos que faria mais sentido escrevermos essas novas features baseadas no *python-consul* e deixarmos o *discovery-client* livre dessas necessidades pontuais ao nosso sistema. 

De qualquer forma, agradecemos o esforço e a colaboração.

**Comment by amenezes** [comment]
Ok. Obrigado.
